import sqlite3, os
db = os.path.join(os.path.dirname(__file__), 'infrastructure', 'persistence', 'lotto.db')
conn = sqlite3.connect(db)
c = conn.cursor()
c.execute("SELECT name FROM sqlite_master WHERE type='table'")
print("Tables:", c.fetchall())
c.execute("SELECT num1,num2,num3,num4,num5,num6,bonus_num FROM lotto_winners WHERE draw_no=1213")
print("1213:", c.fetchone())
c.execute("SELECT num1,num2,num3,num4,num5,num6,bonus_num FROM lotto_winners WHERE draw_no=1212")
print("1212:", c.fetchone())
conn.close()
