-- Postgres 스키마 (Supabase). SQLite schema.sql 대응.
CREATE TABLE IF NOT EXISTS lotto_winners (
    draw_no INTEGER PRIMARY KEY,
    num1 INTEGER NOT NULL,
    num2 INTEGER NOT NULL,
    num3 INTEGER NOT NULL,
    num4 INTEGER NOT NULL,
    num5 INTEGER NOT NULL,
    num6 INTEGER NOT NULL,
    bonus_num INTEGER NOT NULL,
    winner_count INTEGER,
    winner_amount BIGINT
);

CREATE TABLE IF NOT EXISTS lotto_drawings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id TEXT NOT NULL,
    num1 INTEGER NOT NULL,
    num2 INTEGER NOT NULL,
    num3 INTEGER NOT NULL,
    num4 INTEGER NOT NULL,
    num5 INTEGER NOT NULL,
    num6 INTEGER NOT NULL,
    bonus_num INTEGER NOT NULL,
    draw_count INTEGER NOT NULL,
    method TEXT,
    draw_no INTEGER,
    strategy TEXT
);

CREATE TABLE IF NOT EXISTS accumulated_number_snapshots (
    anchor_draw_no INTEGER PRIMARY KEY,
    schema_version INTEGER NOT NULL,
    final_num1 INTEGER NOT NULL,
    final_num2 INTEGER NOT NULL,
    final_num3 INTEGER NOT NULL,
    final_num4 INTEGER NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE lotto_winners ENABLE ROW LEVEL SECURITY;
ALTER TABLE lotto_drawings ENABLE ROW LEVEL SECURITY;
ALTER TABLE accumulated_number_snapshots ENABLE ROW LEVEL SECURITY;
